// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        url: process.env["DATABASE_URL"],
    },
});

// "test:reset": "dotenv -e .env.test -- prisma migrate reset --force",
//         "test": "npm run test:reset && node --experimental-vm-modules node_modules/jest/bin/jest.js"
